//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket.SQLite.Data_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxTable
    {
        public Nullable<int> Id { get; set; }
        public string ProductName { get; set; }
        public decimal Tax { get; set; }
    }
}
